# Generated by Django 5.2.1 on 2025-09-23 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_emischedule_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='emischedule',
            name='last_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emischedule',
            name='late_fee_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DailyTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(default=datetime.date.today)),
                ('run_time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('courses_locked', models.IntegerField(default=0)),
                ('courses_unlocked', models.IntegerField(default=0)),
                ('late_fees_applied', models.IntegerField(default=0)),
                ('reminders_sent', models.IntegerField(default=0)),
                ('total_overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-run_date'],
                'unique_together': {('run_date',)},
            },
        ),
    ]
