# Generated by Django 5.2.1 on 2025-11-17 10:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_devicesession_device_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_code', models.CharField(choices=[('completion', 'Course Completion'), ('achievement', 'Achievement'), ('participation', 'Participation'), ('excellence', 'Excellence'), ('custom', 'Custom')], default='completion', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_file', models.FileField(help_text='Upload HTML template', upload_to='certificate_templates/', validators=[django.core.validators.FileExtensionValidator(['html', 'pdf'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='certificate_thumbnails/')),
                ('orientation', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', max_length=20)),
                ('width', models.IntegerField(default=297)),
                ('height', models.IntegerField(default=210)),
                ('html_content', models.TextField(help_text='HTML template with placeholders')),
                ('css_content', models.TextField(blank=True, help_text='CSS styling')),
                ('available_placeholders', models.JSONField(default=dict, help_text='Available template variables like {student_name}, {course_name}')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='certificates.certificatetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('batch_name', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='certificates/issued/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('verification_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.batch')),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.certificatetype')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.certificatetemplate')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['certificate_id'], name='certificate_certifi_4a4e1e_idx'), models.Index(fields=['student', 'status'], name='certificate_student_4802e0_idx')],
            },
        ),
    ]
