# Generated by Django 5.2.1 on 2025-11-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedcertificate',
            name='duration',
            field=models.CharField(blank=True, help_text='Course duration (3 Months, 12 Weeks)', max_length=100),
        ),
        migrations.AlterField(
            model_name='issuedcertificate',
            name='grade',
            field=models.CharField(blank=True, help_text='Student grade (A+, 95%, etc.)', max_length=50),
        ),
    ]
