# Generated by Django 5.2.1 on 2025-11-06 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for students')),
                ('exam_type', models.CharField(choices=[('mcq', 'Multiple Choice Questions'), ('qa', 'Question & Answer'), ('assignment', 'Assignment Upload')], max_length=20)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('passing_marks', models.PositiveIntegerField(default=40)),
                ('timing_type', models.CharField(choices=[('no_timing', 'No Time Limit'), ('per_question', 'Time Per Question'), ('total_exam', 'Total Exam Time')], default='no_timing', max_length=20)),
                ('time_per_question_minutes', models.PositiveIntegerField(default=2, help_text='Minutes per question (only for per_question timing)')),
                ('total_exam_time_minutes', models.PositiveIntegerField(default=60, help_text='Total exam duration in minutes')),
                ('allow_retake', models.BooleanField(default=False)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('show_results_immediately', models.BooleanField(default=True)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('randomize_options', models.BooleanField(default=False, help_text='For MCQ only')),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['superadmin', 'instructor']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_description', models.TextField()),
                ('submission_guidelines', models.TextField(blank=True)),
                ('allowed_file_types', models.CharField(default='pdf,doc,docx,txt', help_text='Comma-separated file extensions', max_length=200)),
                ('max_file_size_mb', models.PositiveIntegerField(default=10)),
                ('max_files_allowed', models.PositiveIntegerField(default=1)),
                ('evaluation_criteria', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_details', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('individual', 'Individual Student'), ('batch', 'Entire Batch'), ('course', 'Entire Course')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('custom_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('custom_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role__in': ['superadmin', 'instructor']}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to='courses.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to='courses.course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.exam')),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('auto_submitted', 'Auto Submitted (Time Up)'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('exam_config', models.JSONField(default=dict, help_text='Exam settings when attempt was made')),
                ('total_marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_passed', models.BooleanField(default=False)),
                ('is_graded', models.BooleanField(default=False)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_attempts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True)),
                ('uploaded_files', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('feedback', models.TextField(blank=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission', to='exams.examattempt')),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='exam_questions/')),
                ('marks', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='exams.exam')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('option_image', models.ImageField(blank=True, null=True, upload_to='exam_options/')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.mcqquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MCQResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_responses', to='exams.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.mcqquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.mcqoption')),
            ],
        ),
        migrations.CreateModel(
            name='QAQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='exam_questions/')),
                ('marks', models.PositiveIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=1)),
                ('model_answer', models.TextField(blank=True, help_text='Model answer for reference')),
                ('keywords', models.TextField(blank=True, help_text='Key points to look for in answers')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_questions', to='exams.exam')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QAResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('uploaded_files', models.JSONField(blank=True, default=list)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('feedback', models.TextField(blank=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_responses', to='exams.examattempt')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.qaquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ExamFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('qa_response', 'Q&A Response File'), ('assignment', 'Assignment File')], max_length=20)),
                ('file', models.FileField(upload_to='exam_submissions/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.assignmentsubmission')),
                ('qa_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.qaresponse')),
            ],
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type', 'status'], name='exams_exam_exam_ty_975df5_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='exams_exam_start_d_69dfd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examassignment',
            unique_together={('exam', 'batch'), ('exam', 'course'), ('exam', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('exam', 'student', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='mcqquestion',
            unique_together={('exam', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='mcqoption',
            unique_together={('question', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='mcqresponse',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='qaquestion',
            unique_together={('exam', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='qaresponse',
            unique_together={('attempt', 'question')},
        ),
    ]
