# Generated by Django 5.2.1 on 2025-11-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time_per_question_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes per question (only for per_question timing)', null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_exam_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Total exam duration in minutes', null=True),
        ),
    ]
