# Generated by Django 5.2.1 on 2025-09-25 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_batch_batchmodule_batchenrollment_batchlesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('meeting.started', 'Meeting Started'), ('meeting.ended', 'Meeting Ended'), ('meeting.participant_joined', 'Participant Joined'), ('meeting.participant_left', 'Participant Left'), ('recording.completed', 'Recording Completed')], max_length=50)),
                ('zoom_meeting_id', models.CharField(max_length=100)),
                ('event_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('session_type', models.CharField(choices=[('live_class', 'Live Class'), ('doubt_session', 'Doubt Session'), ('workshop', 'Workshop'), ('exam', 'Online Exam')], default='live_class', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoom_meeting_password', models.CharField(blank=True, max_length=50, null=True)),
                ('zoom_join_url', models.URLField(blank=True, null=True)),
                ('zoom_start_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_recorded', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Session',
                'verbose_name_plural': 'Batch Sessions',
                'ordering': ['-scheduled_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ZoomConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='My LMS Organization', max_length=200)),
                ('admin_email', models.EmailField(help_text='Admin email for this Zoom configuration', max_length=254)),
                ('account_id', models.CharField(blank=True, help_text='Your Zoom Account ID from marketplace.zoom.us', max_length=100)),
                ('client_id', models.CharField(blank=True, help_text='Your Zoom App Client ID', max_length=100)),
                ('client_secret', models.CharField(blank=True, help_text='Your Zoom App Client Secret', max_length=100)),
                ('secret_token', models.CharField(blank=True, help_text='Your Zoom App Secret Token for webhooks', max_length=100)),
                ('default_host_video', models.BooleanField(default=True)),
                ('default_participant_video', models.BooleanField(default=True)),
                ('default_join_before_host', models.BooleanField(default=False)),
                ('default_mute_upon_entry', models.BooleanField(default=True)),
                ('default_waiting_room', models.BooleanField(default=True)),
                ('default_auto_recording', models.CharField(choices=[('none', 'No Recording'), ('local', 'Local Recording'), ('cloud', 'Cloud Recording')], default='cloud', max_length=20)),
                ('webhook_url', models.URLField(blank=True, help_text='Auto-generated webhook URL')),
                ('is_active', models.BooleanField(default=False)),
                ('is_configured', models.BooleanField(default=False)),
                ('last_test_date', models.DateTimeField(blank=True, null=True)),
                ('test_status', models.CharField(choices=[('not_tested', 'Not Tested'), ('success', 'Success'), ('failed', 'Failed')], default='not_tested', max_length=20)),
                ('test_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'superadmin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zoom Configuration',
                'verbose_name_plural': 'Zoom Configurations',
            },
        ),
        migrations.CreateModel(
            name='ZoomRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_recording_id', models.CharField(max_length=100, unique=True)),
                ('recording_type', models.CharField(choices=[('cloud', 'Cloud Recording'), ('local', 'Local Recording')], default='cloud', max_length=20)),
                ('file_type', models.CharField(default='mp4', max_length=10)),
                ('download_url', models.URLField()),
                ('play_url', models.URLField(blank=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('recording_start', models.DateTimeField()),
                ('recording_end', models.DateTimeField()),
                ('is_public', models.BooleanField(default=False)),
                ('password_required', models.BooleanField(default=True)),
                ('recording_password', models.CharField(blank=True, max_length=50)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='zoom.batchsession')),
            ],
            options={
                'verbose_name': 'Zoom Recording',
                'verbose_name_plural': 'Zoom Recordings',
                'ordering': ['-recording_start'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('zoom_participant_id', models.CharField(blank=True, max_length=100)),
                ('zoom_user_name', models.CharField(blank=True, max_length=100)),
                ('is_present', models.BooleanField(default=False)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='zoom.batchsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('instructor_rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('technical_rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('overall_rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('feedback_text', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='zoom.batchsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
