# Generated by Django 5.2.1 on 2025-09-25 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_batch_batchmodule_batchenrollment_batchlesson'),
        ('zoom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batchsession',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batchsession',
            name='parent_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_sessions', to='zoom.batchsession'),
        ),
        migrations.AddField(
            model_name='batchsession',
            name='recurring_days',
            field=models.CharField(blank=True, help_text='For weekly: 1,2,3,4,5,6,7 (Mon-Sun)', max_length=20),
        ),
        migrations.AddField(
            model_name='batchsession',
            name='recurring_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchsession',
            name='recurring_type',
            field=models.CharField(choices=[('none', 'Single Session'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Days')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='batchsession',
            name='session_sequence',
            field=models.IntegerField(default=1, help_text='Session number in recurring series'),
        ),
        migrations.AddIndex(
            model_name='batchsession',
            index=models.Index(fields=['batch', 'scheduled_date'], name='zoom_batchs_batch_i_9bffe0_idx'),
        ),
        migrations.AddIndex(
            model_name='batchsession',
            index=models.Index(fields=['status', 'scheduled_date'], name='zoom_batchs_status_a67240_idx'),
        ),
        migrations.AddIndex(
            model_name='batchsession',
            index=models.Index(fields=['parent_session'], name='zoom_batchs_parent__3f2c9f_idx'),
        ),
    ]
