# Generated by Django 5.2.1 on 2025-09-25 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_batchsession_is_recurring_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionattendance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Session Attendance', 'verbose_name_plural': 'Session Attendances'},
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='manually_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional attendance notes'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of session attended', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
