# Generated by Django 5.2.1 on 2025-11-07 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='batch_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.batchlesson'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='course_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.courselesson'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['student', 'course_lesson'], name='courses_les_student_d75f12_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['student', 'batch_lesson'], name='courses_les_student_d45c1d_idx'),
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='lesson',
        ),
    ]
