# Generated by Django 5.2.1 on 2025-11-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
