# Generated by Django 5.2.1 on 2025-09-03 06:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Additional notes or instructions'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Lesson duration in minutes'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='is_free_preview',
            field=models.BooleanField(default=False, help_text='Can be viewed without enrollment'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='is_mandatory',
            field=models.BooleanField(default=True, help_text='Required for course completion'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='lesson_type',
            field=models.CharField(choices=[('text', 'Text Content'), ('video', 'Video'), ('pdf', 'PDF Document'), ('mixed', 'Mixed Content')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF document', null=True, upload_to='lesson_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='text_content',
            field=models.TextField(blank=True, help_text='Rich text content for the lesson'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (mp4, avi, mkv, mov)', null=True, upload_to='lesson_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mkv', 'mov'])]),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='vimeo_url',
            field=models.URLField(blank=True, help_text='Vimeo URL'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo URL'),
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='lesson_attachments/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'zip', 'rar', 'txt', 'jpg', 'png', 'gif'])])),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.courselesson')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.courselesson')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed'],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
