# Generated by Django 5.2.1 on 2025-11-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courselesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesession',
            name='device_id',
            field=models.CharField(help_text='SHA256 fingerprint', max_length=200),
        ),
    ]
