# Generated by Django 5.2.1 on 2025-10-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_studentloginlog_studentsubscription_devicesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='attendance_radius_meters',
            field=models.IntegerField(default=50, help_text='Allowed distance for marking attendance'),
        ),
        migrations.AddField(
            model_name='batch',
            name='building_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='batch',
            name='classroom_capacity',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='batch',
            name='classroom_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='batch',
            name='delivery_mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='batch',
            name='floor_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('live', 'Live Classes'), ('recorded', 'Recorded'), ('hybrid', 'Hybrid'), ('offline', 'Offline')], default='live', max_length=20),
        ),
    ]
