# Generated by Django 5.2.1 on 2025-09-06 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyemailsummary',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-sent_time']},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emailtemplatetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailtemplatetype',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplatetype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create_user', 'Created User'), ('update_user', 'Updated User'), ('delete_user', 'Deleted User'), ('create_course', 'Created Course'), ('update_course', 'Updated Course'), ('enroll_course', 'Enrolled in Course'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked')], max_length=25),
        ),
        migrations.CreateModel(
            name='InstructorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text="Unique code like 'content_management'", max_length=50, unique=True)),
                ('description', models.TextField(help_text='What this permission allows')),
                ('category', models.CharField(help_text="Category like 'Course Management', 'Email Marketing'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'superadmin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor Permission',
                'verbose_name_plural': 'Instructor Permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('qualification', models.TextField(blank=True, help_text='Educational qualifications')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('office_location', models.CharField(blank=True, max_length=100)),
                ('office_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval for teaching')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'superadmin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_instructor_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor Profile',
                'verbose_name_plural': 'Instructor Profiles',
            },
        ),
        migrations.CreateModel(
            name='InstructorPermissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this permission')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Permission expiry date', null=True)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role': 'superadmin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userss.instructorpermission')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='userss.instructorprofile')),
            ],
            options={
                'verbose_name': 'Instructor Permission Assignment',
                'verbose_name_plural': 'Instructor Permission Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('instructor', 'permission')},
            },
        ),
    ]
