# Generated by Django 5.2.1 on 2025-11-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0002_emailconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(help_text='Your Gmail address', max_length=254)),
                ('email_host_password', models.CharField(help_text='Gmail App Password', max_length=255)),
                ('default_from_email', models.EmailField(help_text='Display email for outgoing mails', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Email SMTP Configuration',
                'verbose_name_plural': 'Email SMTP Configurations',
            },
        ),
        migrations.DeleteModel(
            name='EmailConfiguration',
        ),
    ]
