# Generated by Django 5.2.1 on 2025-09-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0003_alter_dailyemailsummary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('instructor', 'Instructor'), ('student', 'Student'), ('webinar_user', 'Webinar User')], default='student', max_length=20),
        ),
    ]
