# Generated by Django 5.2.1 on 2025-09-21 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Webinar Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=300)),
                ('webinar_type', models.CharField(choices=[('free', 'Free Webinar'), ('paid', 'Paid Webinar')], default='free', max_length=10)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live Now'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration in minutes')),
                ('max_attendees', models.PositiveIntegerField(default=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='webinar_thumbnails/')),
                ('webinar_link', models.URLField(blank=True, help_text='Zoom/Meet/Teams link')),
                ('meeting_id', models.CharField(blank=True, max_length=50)),
                ('meeting_password', models.CharField(blank=True, max_length=50)),
                ('learning_outcomes', models.TextField(help_text='What attendees will learn')),
                ('prerequisites', models.TextField(blank=True, help_text='What attendees should know')),
                ('send_reminder_emails', models.BooleanField(default=True)),
                ('reminder_hours_before', models.PositiveIntegerField(default=24, help_text='Send reminder X hours before')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_registrations', models.PositiveIntegerField(default=0)),
                ('actual_attendees', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webinars', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(limit_choices_to={'role__in': ['instructor', 'superadmin']}, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_webinars', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinars', to='webinars.webinarcategory')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='WebinarFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')])),
                ('instructor_rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')])),
                ('overall_rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')])),
                ('what_you_liked', models.TextField(blank=True)),
                ('suggestions_for_improvement', models.TextField(blank=True)),
                ('would_recommend', models.BooleanField(default=True)),
                ('interested_in_similar_webinars', models.BooleanField(default=True)),
                ('interested_in_paid_courses', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='webinars.webinar')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('join_link_sent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('attended_duration_minutes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_registrations', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='webinars.webinar')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='webinar_resources/')),
                ('is_available_before_webinar', models.BooleanField(default=False, help_text='Make available to registered users before webinar')),
                ('is_available_after_webinar', models.BooleanField(default=True, help_text='Make available after webinar completion')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='webinars.webinar')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['status', 'webinar_type'], name='webinars_we_status_e08ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='webinar',
            index=models.Index(fields=['scheduled_date'], name='webinars_we_schedul_2c6150_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webinarfeedback',
            unique_together={('webinar', 'attendee')},
        ),
        migrations.AlterUniqueTogether(
            name='webinarregistration',
            unique_together={('webinar', 'email')},
        ),
    ]
