# Generated by Django 5.2.1 on 2025-09-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
