# Generated by Django 5.2.1 on 2025-10-11 06:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_batch_attendance_radius_meters_batch_building_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom_location', models.CharField(help_text='e.g., Main Office, Room 101', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Classroom latitude (Google Maps se copy karo)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Classroom longitude (Google Maps se copy karo)', max_digits=9)),
                ('allowed_radius_meters', models.IntegerField(default=50, help_text='Students must be within this radius')),
                ('qr_code', models.ImageField(blank=True, upload_to='attendance_qr/')),
                ('qr_secret', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='courses.batch')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'unique_together': {('batch', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marking_method', models.CharField(choices=[('qr_scan', 'QR Code Scan'), ('manual', 'Manual by Instructor')], default='qr_scan', max_length=20)),
                ('student_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('student_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_from_classroom', models.IntegerField(blank=True, help_text='Distance in meters from classroom', null=True)),
                ('is_present', models.BooleanField(default=True)),
                ('is_late', models.BooleanField(default=False)),
                ('is_within_radius', models.BooleanField(default=False, help_text='Was student within allowed radius?')),
                ('notes', models.TextField(blank=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['-marked_at'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
