# Generated by Django 5.2.1 on 2025-11-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualattendancerequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin/Instructor notes about approval/rejection'),
        ),
        migrations.AddField(
            model_name='manualattendancerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When was this request processed', null=True),
        ),
        migrations.AddField(
            model_name='manualattendancerequest',
            name='request_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Student's latitude when requesting", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='manualattendancerequest',
            name='request_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Student's longitude when requesting", max_digits=9, null=True),
        ),
    ]
