# Generated by Django 5.2.1 on 2025-10-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_manualattendancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
