# Generated by Django 5.2.1 on 2025-11-07 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_manualattendancerequest_admin_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manualattendancerequest',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='manualattendancerequest',
            index=models.Index(fields=['session', 'student', 'status'], name='attendance__session_2dcaec_idx'),
        ),
    ]
