# Generated by Django 5.2.1 on 2025-10-13 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancesession_end_time_and_more'),
        ('courses', '0005_batch_attendance_radius_meters_batch_building_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'student')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='allowed_radius_meters',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.batch'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='classroom_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Session end time (with date and timezone)', null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='instructor',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'instructor')), on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='qr_secret',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Session start time (with date and timezone)'),
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='qr_code',
        ),
    ]
