# Generated by Django 5.2.1 on 2025-10-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancesession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Generated QR code image', null=True, upload_to='attendance_qr_codes/'),
        ),
    ]
